# fly.toml app configuration file generated for dgms-library on 2025-07-09T16:03:28Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dgms-library'
primary_region = 'fra'
kill_signal = 'SIGINT'
kill_timeout = '5s'
console_command = '/app/manage.py shell'

[experimental]
  auto_rollback = true

[build]

[deploy]
  release_command = 'python manage.py migrate'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 500
    soft_limit = 400

[checks]
  [checks.health]
    port = 8080
    type = 'http'
    interval = '15s'
    timeout = '2s'
    grace_period = '30s'
    method = 'GET'
    path = '/health/'
    protocol = 'http'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/app/static'
  url_prefix = '/static/'

# Metrics endpoint removed - not implemented in Django app
# [[metrics]]
#   port = 8080
#   path = '/metrics'
